Repository greenmg2003/osu-mg-reload, pull requests merged in 2025-05, with the labels that each got.

#63 Bug-fix for 4.1.3
  Hitsounds.rar
  README.md
  mode-osu-med.png
  ranking-panel.png
  ranking-panel@2x.png
  scorebar-bg.png
  skin.ini
  spinner-approachcircle.png
Labels: bug, documentation, UI

#64 4.2.3 Bug-fix Update
  README.md
  lighting.png
  mode-osu-med.png
  ranking-panel.png
  ranking-panel@2x.png
  scorebar-bg.png
  skin.ini
Labels: documentation, potential:4, UI

#66 5.0.3 bug-fix update
  README.md
  ranking-panel.png
  ranking-panel@2x.png
Labels: documentation, potential:4, UI

#65 Update attachment for main branch
  README.md
Labels: documentation

#67 Format fix
  README.md
Labels: documentation

#68 Format fix (again)
  README.md
Labels: documentation

#71 Contribute rule rework
  CONTRIBUTING.md
Labels: documentation

#74 Banner Update - Season 1
  README.md
Labels: documentation, potential:5
