Repository greenmg2003/osu-mg-reload, pull requests merged in 2025-04, with the labels that each got.

#52 UI revamp, final part for 5.0.2
  mode-fruits-med.png
  mode-mania-med.png
  mode-osu-med.png
  mode-taiko-med.png
  ranking-A-small.png
  ranking-A-small@2x.png
  ranking-A.png
  ranking-A@2x.png
  ranking-B-small.png
  ranking-B-small@2x.png
  ranking-B.png
  ranking-B@2x.png
  ranking-C-small.png
  ranking-C-small@2x.png
  ranking-C.png
  ranking-C@2x.png
  ranking-D-small.png
  ranking-D-small@2x.png
  ranking-D.png
  ranking-D@2x.png
  ranking-S-small.png
  ranking-S-small@2x.png
  ranking-S.png
  ranking-S@2x.png
  ranking-SH-small.png
  ranking-SH-small@2x.png
  ranking-SH.png
  ranking-SH@2x.png
  ranking-X-small.png
  ranking-X-small@2x.png
  ranking-X.png
  ranking-X@2x.png
  ranking-XH-small.png
  ranking-XH-small@2x.png
  ranking-XH.png
  ranking-XH@2x.png
  ranking-panel.png
  ranking-panel@2x.png
Labels: enhancement, UI, Release

#53 UI Revamp, final part for 4.2.2
  mode-fruits-med.png
  mode-mania-med.png
  mode-osu-med.png
  mode-taiko-med.png
  ranking-A-small.png
  ranking-A-small@2x.png
  ranking-A.png
  ranking-A@2x.png
  ranking-B-small.png
  ranking-B-small@2x.png
  ranking-B.png
  ranking-B@2x.png
  ranking-C-small.png
  ranking-C-small@2x.png
  ranking-C.png
  ranking-C@2x.png
  ranking-D-small.png
  ranking-D-small@2x.png
  ranking-D.png
  ranking-D@2x.png
  ranking-S-small.png
  ranking-S-small@2x.png
  ranking-S.png
  ranking-S@2x.png
  ranking-SH-small.png
  ranking-SH-small@2x.png
  ranking-SH.png
  ranking-SH@2x.png
  ranking-X-small.png
  ranking-X-small@2x.png
  ranking-X.png
  ranking-X@2x.png
  ranking-XH-small.png
  ranking-XH-small@2x.png
  ranking-XH.png
  ranking-XH@2x.png
  ranking-panel.png
  ranking-panel@2x.png
Labels: enhancement, UI, Release

#54 UI revamp, final part for 4.1.2
  mode-fruits-med.png
  mode-mania-med.png
  mode-osu-med.png
  mode-taiko-med.png
  ranking-A-small.png
  ranking-A.png
  ranking-B-small.png
  ranking-B.png
  ranking-C-small.png
  ranking-C.png
  ranking-D-small.png
  ranking-D.png
  ranking-S-small.png
  ranking-S.png
  ranking-SH-small.png
  ranking-SH.png
  ranking-X-small.png
  ranking-X.png
  ranking-XH-small.png
  ranking-XH.png
  ranking-panel.png
  ranking-panel@2x.png
Labels: enhancement, UI, Release

#59 Update README.md for 4.2.2
  README.md
Labels: documentation, Release

#58 Update README.md for 4.1.2 branch
  README.md
Labels: documentation, Release

#60 v.5.0.3 Update
  pippidonclear0.png
  pippidonclear0@2x.png
  pippidonclear1.png
  pippidonclear1@2x.png
  pippidonclear2.png
  pippidonclear2@2x.png
  pippidonclear3.png
  pippidonclear3@2x.png
  pippidonclear4.png
  pippidonclear4@2x.png
  pippidonclear5.png
  pippidonclear5@2x.png
  pippidonfail0.png
  pippidonfail0@2x.png
  pippidonfail1.png
  pippidonfail1@2x.png
  pippidonidle0.png
  pippidonidle0@2x.png
  pippidonidle1.png
  pippidonidle1@2x.png
  pippidonidle2.png
  pippidonidle2@2x.png
  pippidonidle3.png
  pippidonidle3@2x.png
  pippidonkiai0.png
  pippidonkiai0@2x.png
  pippidonkiai1.png
  pippidonkiai1@2x.png
  pippidonkiai2.png
  pippidonkiai2@2x.png
  pippidonkiai3.png
  pippidonkiai3@2x.png
  scorebar-bg.png
  skin.ini
Labels: enhancement, UI, taiko, File upload
