Repository greenmg2003/osu-mg-reload, pull requests merged in 2025-03, with the labels that each got.

#39 Final patch for this batch, I swear ;w;
  README.md
Labels: documentation, enhancement, potential:4, Completed!

#40 Upload Part 1 - 3.1.x - Keys
  Keys/Down.png
  Keys/Down@2x.png
  Keys/Left.png
  Keys/Left@2x.png
  Keys/Right.png
  Keys/Right@2x.png
  Keys/Up.png
  Keys/Up@2x.png
Labels: File upload

#48 Bug fix skin.ini
  skin.ini
Labels: bug

#49 Update FAQ file
  faq-about-the-project.md
Labels: documentation
